# -*- mode: ruby -*-
# vi: set ft=ruby :

USER_NAME = 'dev'
HOST_AON_PARENT_PATH="/home/eagirrezabal/git/AON-MASTER-UDAPA/aon.parent"
HOST_FOLDER_JASPERREPORTS="/home/eagirrezabal/git/AON-MASTER-UDAPA/aon.parent/aon-jasperreports"
HOST_FOLDER_COMMONRESOURCES="/home/eagirrezabal/git/AON-MASTER-UDAPA/aon.parent/aon-common-resources"
#HOST_IP='192.168.2.213'
HOST_IP='192.168.3.43'
VM_CPU=4
VM_MEMORY="4096"

