# -*- mode: ruby -*-
# vi: set ft=ruby :
require './config'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = VM_CPU
    vb.memory = VM_MEMORY
  end
  config.landrush.enabled = true
  config.vm.define vm_name = "dev" do |config|
    config.cache.scope = :box
    config.vm.hostname = vm_name
    config.landrush.tld = vm_name
    config.vm.network "private_network", ip: GUEST_IP
  end
  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision :shell, :path => "setup.sh", :args => [USER_NAME]
## SYNCED FOLDER: enable after first 'vagrant up', when user exist
  SYNCED_FOLDERS.each do |folder|
    config.vm.synced_folder SYNCED_FOLDERS_PATH+folder, folder,
      owner: USER_NAME, group: USER_NAME, mount_options: ["dmode=775,fmode=664"], disabled: SYNCED_FOLDERS_ENABLED
  end
## Landrush host entries
  DNS_ENTRIES.each do |entry|
    config.landrush.host entry, DNS_IP
  end

end
