# -*- mode: ruby -*-
# vi: set ft=ruby :
require './config'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = VM_CPU
    vb.memory = VM_MEMORY
  end
  config.landrush.enabled = true
  config.vm.define vm_name = "dev" do |config|
    config.cache.scope = :box
    config.vm.hostname = vm_name
    config.landrush.tld = vm_name
    config.vm.network "private_network", ip: GUEST_IP
  end
  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision :shell, :path => "setup.sh", :args => [USER_NAME]
## SYNCED FOLDER: enable after first 'vagrant up', when user exist
  config.vm.synced_folder HOST_AON_PARENT_PATH+"/aon-jasperreports", "/aon-jasperreports",
    owner: USER_NAME, group: USER_NAME, mount_options: ["dmode=775,fmode=664"], disabled: false
  config.vm.synced_folder HOST_AON_PARENT_PATH+"/aon-common-resources", "/aon-common-resources",
    owner: USER_NAME, group: USER_NAME, mount_options: ["dmode=775,fmode=664"], disabled: false
## Landrush host entries
  config.landrush.host 'esferalia.net', HOST_IP
  config.landrush.host 'aonsolutions.me', HOST_IP
  config.landrush.host 'grupoplayasol.com', HOST_IP
#  config.landrush.host_interface_excludes = [/lo[0-9]*/, /docker[0-9]+/, /tun[0-9]+/]
#  config.landrush.host_interface_class = :ipv4
#  config.landrush.host_interface = 'eno1'
end
